# Generated by Django 6.1 on 2026-08-27 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='الإيميل')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='الإيميل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('cv_file', models.FileField(upload_to='cvs/', verbose_name='السيرة الذاتية (PDF)')),
                ('message', models.TextField(blank=True, null=True, verbose_name='رسالة إضافية')),
                ('status', models.CharField(choices=[('pending', 'في انتظار المراجعة'), ('approved', 'تم الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المشرف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سيرة ذاتية',
                'verbose_name_plural': 'السير الذاتية',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
