# Generated by Django 6.1 on 2026-08-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminActivityLog',
        ),
    ]
